<?php

//This file will write a php config file to be included during execution of all helpdesk  file for configuration.

// deny all but system admins
$canEdit = !getDenyEdit( 'system' );
if (!$canEdit) {
	$AppUI->redirect( "m=public&a=access_denied" );
}

@include_once( "./functions/admin_func.php" );

$CONFIG_FILE = "./modules/helpdesk/config.php";

$AppUI->savePlace();

/*
pending
-HTMLArea, on/off
-available search criteria on the list screen

done
-default assigned to to current user
- Notify by email
- Default company to current user 
*/

//All config options, their descriptions and their default values are defined here.  
//Add new config options here.  type can be "checkbox", "text", or "select".  If it's "select"
//then be sure to include a 'list' entry with the options.
$config_options = array(
	"items_per_page" => array(
		"description" => $AppUI->_('Number of items displayed per page on the list view.'),
		"value" => 30,
		'type' => 'text'
	),
	"status_log_items_per_page" => array(
		"description" => $AppUI->_('Number of status log items displayed per page in item view.'),
		"value" => 15,
		'type' => 'text'
	),
	"pages_per_set" => array(
		"description" => $AppUI->_('Number of pages to display per page set.'),
		"value" => 5,
		'type' => 'text'
	),
	"default_assigned_to_current_user" => array(
		"description" => $AppUI->_('Defaults that "assigned to" field to be that of the current user.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"default_notify_by_email" => array(
		"description" => $AppUI->_('Defaults the "notify by email" field to on.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"default_company_current_company" => array(
		"description" => $AppUI->_('Defaults the "company" field to be that of the current user.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_search" => array(
		"description" => $AppUI->_('Show the search option for Title Search.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_call_type" => array(
		"description" => $AppUI->_('Show the search option for Call Type.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_company" => array(
		"description" => $AppUI->_('Show the search option for Company.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_status" => array(
		"description" => $AppUI->_('Show the search option for Status.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_call_source" => array(
		"description" => $AppUI->_('Show the search option for Call Source.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_project" => array(
		"description" => $AppUI->_('Show the search option for Project.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_assigned_to" => array(
		"description" => $AppUI->_('Show the search option for Assigned To.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_priority" => array(
		"description" => $AppUI->_('Show the search option for Priority.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_application" => array(
		"description" => $AppUI->_('Show the search option for Application.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_requestor" => array(
		"description" => $AppUI->_('Show the search option for Requestor.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_severity" => array(
		"description" => $AppUI->_('Show the search option for Severity.'),
		"value" => 1,
		'type' => 'checkbox'
	),
	"search_criteria_os" => array(
		"description" => $AppUI->_('Show the search option for Operation System.'),
		"value" => 1,
		'type' => 'checkbox'
	)

);

//if this is a submitted page, overwrite the config file.
if(dPgetParam( $_POST, "Save", '' )!=''){

	if (is_writable($CONFIG_FILE)) {
		if (!$handle = fopen($CONFIG_FILE, 'w')) {
			$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('cannot be opened.'), UI_MSG_ERROR );
			exit;
		}

		if (fwrite($handle, "<?php //Do not edit this file by hand, it will be overwritting by the configuration utility. \n") === FALSE) {
			$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('cannot be written to.'), UI_MSG_ERROR );
			exit;
		} else {
			foreach ($config_options as $key=>$value){
				$val="";
				switch($value['type']){
					case 'checkbox': 
						$val = isset($_POST[$key])?"1":"0";
						break;
					case 'text': 
						$val = isset($_POST[$key])?$_POST[$key]:"";
						break;
					case 'select': 
						$val = isset($_POST[$key])?$_POST[$key]:"0";
						break;
					default:
						break;
				}
				
				fwrite($handle, "\$HELPDESK_CONFIG['".$key."'] = '".$val."';\n");
			}

			fwrite($handle, "?> \n");
			$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('has been successfully updated.'), UI_MSG_OK );
			fclose($handle);
		}
	} else {
		$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('is not writable.'), UI_MSG_ERROR );
	}
} else if(dPgetParam( $_POST, "Cancel", '' )!=''){
	$AppUI->redirect("m=system&a=viewmods");
}


$HELPDESK_CONFIG = array();
require_once( $CONFIG_FILE );

//Read the current config values from the config file and update the array.
foreach ($config_options as $key=>$value){
	if(isset($HELPDESK_CONFIG[$key])){

		$config_options[$key]['value']=$HELPDESK_CONFIG[$key];
	}
}

// setup the title block
$titleBlock = new CTitleBlock( 'Configure Help Desk Module', 'helpdesk.png', $m, "$m.$a" );
$titleBlock->addCrumb( "?m=system", "system admin" );
$titleBlock->addCrumb( "?m=system&a=viewmods", "modules list" );
$titleBlock->show();

?>

<form method="post">
<table class="std">
<?php
foreach ($config_options as $key=>$value){
?>
	<tr>
		<td align="left"><?=$value['description']?></td>
		<td><?php
		switch($value['type']){
			case 'checkbox': ?>
				<input type="checkbox" name="<?=$key?>" <?=$value['value']?"checked=\"checked\"":""?>>
				<?php
				break;
			case 'text': ?>
				<input type="text" name="<?=$key?>" value="<?=$value['value']?>">
				<?php
				break;
			case 'select': 
				print arraySelect( $value["list"], $key, 'class=text size=1', $value["value"] );
				break;
			default:
				break;
		}
		?></td>
	</tr>
<?php	
}
?>
	<tr>
		<td colspan="2" align="right"><input type="Submit" name="Cancel" value="<?=$AppUI->_('Back')?>"><input type="Submit" name="Save" value="<?=$AppUI->_('Save')?>"></td>
	</tr>
</table>
</form>
