<?php //Do not edit this file by hand, it will be overwritting by the configuration utility. 
$HELPDESK_CONFIG['default_assigned_to_current_user'] = 1;
$HELPDESK_CONFIG['default_notify_by_email'] = 1;
$HELPDESK_CONFIG['default_company_current_company'] = 1;
?> 
