<?php //Do not edit this file by hand, it will be overwritting by the configuration utility. 
$HELPDESK_CONFIG['items_per_page'] = '30';
$HELPDESK_CONFIG['status_log_items_per_page'] = '10';
$HELPDESK_CONFIG['default_assigned_to_current_user'] = '1';
$HELPDESK_CONFIG['default_notify_by_email'] = '1';
$HELPDESK_CONFIG['default_company_current_company'] = '1';
$HELPDESK_CONFIG['search_criteria_search'] = '1';
$HELPDESK_CONFIG['search_criteria_call_type'] = '1';
$HELPDESK_CONFIG['search_criteria_company'] = '1';
$HELPDESK_CONFIG['search_criteria_status'] = '1';
$HELPDESK_CONFIG['search_criteria_call_source'] = '1';
$HELPDESK_CONFIG['search_criteria_project'] = '1';
$HELPDESK_CONFIG['search_criteria_assigned_to'] = '1';
$HELPDESK_CONFIG['search_criteria_priority'] = '1';
$HELPDESK_CONFIG['search_criteria_application'] = '1';
$HELPDESK_CONFIG['search_criteria_requestor'] = '1';
$HELPDESK_CONFIG['search_criteria_severity'] = '1';
$HELPDESK_CONFIG['search_criteria_os'] = '1';
?> 
