<?php

//This file will write a php config file to be included during execution of all helpdesk  file for configuration.

// deny all but system admins
$canEdit = !getDenyEdit( 'system' );
if (!$canEdit) {
	$AppUI->redirect( "m=public&a=access_denied" );
}

$CONFIG_FILE = "./modules/helpdesk/config.php";

$AppUI->savePlace();

/*
pending
-HTMLArea, on/off
-available search criteria on the list screen

done
-default assigned to to current user
- Notify by email
- Default company to current user 
*/

//All config options, their descriptions and their default values are defined here.  
$config_options = array(
	"default_assigned_to_current_user" => array(
		"description" => $AppUI->_('Defaults that "assigned to" field to be that of the current user.'),
		"value" => 1
	),
	"default_notify_by_email" => array(
		"description" => $AppUI->_('Defaults the "notify by email" field to on.'),
		"value" => 1
	),
	"default_company_current_company" => array(
		"description" => $AppUI->_('Defaults the "company" field to be that of the current user.'),
		"value" => 1
	),
	"search_criteria_search" => array(
		"description" => $AppUI->_('Show the search option for Title Search.'),
		"value" => 1
	),
	"search_criteria_call_type" => array(
		"description" => $AppUI->_('Show the search option for Call Type.'),
		"value" => 1
	),
	"search_criteria_company" => array(
		"description" => $AppUI->_('Show the search option for Company.'),
		"value" => 1
	),
	"search_criteria_status" => array(
		"description" => $AppUI->_('Show the search option for Status.'),
		"value" => 1
	),
	"search_criteria_call_source" => array(
		"description" => $AppUI->_('Show the search option for Call Source.'),
		"value" => 1
	),
	"search_criteria_project" => array(
		"description" => $AppUI->_('Show the search option for Project.'),
		"value" => 1
	),
	"search_criteria_assigned_to" => array(
		"description" => $AppUI->_('Show the search option for Assigned To.'),
		"value" => 1
	),
	"search_criteria_priority" => array(
		"description" => $AppUI->_('Show the search option for Priority.'),
		"value" => 1
	),
	"search_criteria_application" => array(
		"description" => $AppUI->_('Show the search option for Application.'),
		"value" => 1
	),
	"search_criteria_requestor" => array(
		"description" => $AppUI->_('Show the search option for Requestor.'),
		"value" => 1
	),
	"search_criteria_severity" => array(
		"description" => $AppUI->_('Show the search option for Severity.'),
		"value" => 1
	),
	"search_criteria_os" => array(
		"description" => $AppUI->_('Show the search option for Operation System.'),
		"value" => 1
	)

);

//if this is a submitted page, overwrite the config file.
if(dPgetParam( $_POST, "Save", '' )!=''){

	if (is_writable($CONFIG_FILE)) {
		if (!$handle = fopen($CONFIG_FILE, 'w')) {
			$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('cannot be opened.'), UI_MSG_ERROR );
			exit;
		}

		if (fwrite($handle, "<?php //Do not edit this file by hand, it will be overwritting by the configuration utility. \n") === FALSE) {
			$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('cannot be written to.'), UI_MSG_ERROR );
			exit;
		} else {
			foreach ($config_options as $key=>$value){
				$val = isset($_POST[$key])?"1":"0";

				fwrite($handle, "\$HELPDESK_CONFIG['".$key."'] = ".$val.";\n");
			}

			fwrite($handle, "?> \n");
			$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('has been successfully updated.'), UI_MSG_OK );
			fclose($handle);
		}
	} else {
		$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('is not writable.'), UI_MSG_ERROR );
	}
} else if(dPgetParam( $_POST, "Cancel", '' )!=''){
	$AppUI->redirect("m=system&a=viewmods");
}

$HELPDESK_CONFIG = array();
require_once( $CONFIG_FILE );

//Read the current config values from the config file and update the array.
foreach ($config_options as $key=>$value){
	if(isset($HELPDESK_CONFIG[$key])){

		$config_options[$key]['value']=$HELPDESK_CONFIG[$key];
	}
}

// setup the title block
$titleBlock = new CTitleBlock( 'Configure Help Desk Module', 'helpdesk.png', $m, "$m.$a" );
$titleBlock->addCrumb( "?m=system", "system admin" );
$titleBlock->addCrumb( "?m=system&a=viewmods", "modules list" );
$titleBlock->show();

?>

<form method="post">
<table class="std">
<?php
foreach ($config_options as $key=>$value){
?>
	<tr>
		<td align="left"><?=$value['description']?></td>
		<td><input type="checkbox" name="<?=$key?>" <?=$value['value']?"checked":""?>></td>
	</tr>
<?php	
}
?>
	<tr>
		<td colspan="2" align="right"><input type="Submit" name="Cancel" value="<?=$AppUI->_('Back')?>"><input type="Submit" name="Save" value="<?=$AppUI->_('Save')?>"></td>
	</tr>
</table>
</form>
